# Generated by Django 4.0.3 on 2022-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
