# Generated by Django 4.0.3 on 2026-04-09

from django.db import migrations, models
import django.core.validators
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='demo_video',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='items/demo_videos',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['mp4', 'webm', 'ogg', 'mov']
                    ),
                    items.models.validate_demo_video_size,
                ],
            ),
        ),
    ]
